apps/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('blog-details/<int:pk>', blog_details, name='blog-details'),
]

apps/carts/urls.py
from django.urls import path
from .views import *

app_name = 'carts'

urlpatterns = [
    path('', cart, name='cart'),
    path('add-wishlist/', add_wishlist, name='add-wishlist'),
    path('my-wishlist/', my_wishlist, name='my-wishlist'),
    path('add-cart/', add_cart, name='add-cart'),
    path('plus-quantity/', plus_quantity, name='plus_quantity'),
    path('minus-quantity/', minus_quantity, name='minus_quantity'),
    path('delete-cart-item/', delete_cart_item, name='delete_cart_item'),
    path('checkout/', checkout, name='checkout'),
]

apps/contacts/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('', contact, name='contact'),
]

apps/products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('', home, name='home'),
    path('shop-details/<int:pid>', shop_details, name='shop-details'),
    path('shop-grid/', shop_grid, name='shop_grid'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # allauth
    path('accounts/', include('allauth.urls')),

    # local urls
    path('', include('apps.products.urls', namespace='products')),
    path('carts/', include('apps.carts.urls', namespace='carts')),
    path('contacts/', include('apps.contacts.urls', namespace='contacts')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('profile/', include('apps.accounts.urls', namespace='accounts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # /media/user/user.png

apps/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from apps.products.models import Category


# Create your models here.

class Tag(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return self.tag


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    content = models.TextField()
    author_name = models.CharField(max_length=255)
    author_image = models.ImageField(upload_to='author')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

apps/contacts/models.py
from django.db import models


# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

apps/contacts/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

apps/blog/views.py
from django.shortcuts import render, redirect
from .models import *
from apps.products.models import Category


# Create your views here.

def blog(request):
    posts = Post.objects.order_by('-id')[:6]
    last_3_posts = Post.objects.order_by('-id')[:3]
    tags = Tag.objects.all()
    s = request.GET.get('s')
    if s:
        posts = Post.objects.filter(title__icontains=s)
    cat = request.GET.get('cat')
    if cat:
        posts = Post.objects.filter(category__category__exact=cat)
    tag = request.GET.get('tag')
    if tag:
        posts = Post.objects.filter(tags__tag__exact=tag)
    ctx = {
        'posts': posts,
        'last_3_posts': last_3_posts,
        'tags': tags
    }
    return render(request, 'blog.html', ctx)


def blog_details(request, pk):
    post = Post.objects.get(id=pk)
    last_3_posts = Post.objects.order_by('-id')[:3]
    tags = Tag.objects.all()
    ctx = {
        'post': post,
        'last_3_posts': last_3_posts,
        'tags': tags
    }
    return render(request, 'blog-details.html', ctx)

apps/contacts/views.py
from django.shortcuts import render
from .forms import ContactForm
from .models import Subscribe
from apps.products.models import Category


# Create your views here.

def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
    email = request.GET.get('email')
    if email:
        Subscribe.objects.create(email=email)
    ctx = {
        'form': form,
    }
    return render(request, 'contact.html', ctx)

templates/blog-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="hero hero-normal">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All departments</span>
                    </div>
                    <ul>
                        {% for category in categories %}
                            <li><a href=".">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form method="get" action="/blog/">
                            <input type="search" name="s" placeholder="What do you need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>+998 88 910 67 63</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="blog-details-hero set-bg" data-setbg="{% static 'img/blog/details/details-hero.jpg.webp' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="blog__details__hero__text">
                    <h2>The Moment You Need To Remove Garlic From The Menu</h2>
                    <ul>
                        <li>By {{ post.author_name }}</li>
                        <li>{{ post.created_at }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="blog-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-5 order-md-1 order-2">
                <div class="blog__sidebar">
                    <div class="blog__sidebar__search">
                        <form method="get" action="/blog/">
                            <input type="search" name="s" placeholder="Search...">
                            <button type="submit"><span class="icon_search"></span></button>
                        </form>
                    </div>
                    <div class="blog__sidebar__item">
                        <h4>Categories</h4>
                        <ul>
                            {% for category in categories %}
                                <li><a href="/blog/?cat={{ category }}">{{ category }} ({{ category.post_set.count }})</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="blog__sidebar__item">
                        <h4>Recent News</h4>
                        <div class="blog__sidebar__recent">
                            {% for last_3_post in last_3_posts %}
                                <a href="{% url 'blog:blog-details' last_3_post.id %}" class="blog__sidebar__recent__item">
                                <div class="blog__sidebar__recent__item__pic">
                                    <img height="80px" src="{{ last_3_post.image.url }}" alt="">
                                </div>
                                <div class="blog__sidebar__recent__item__text">
                                    <h6>{{ last_3_post.title|slice:75 }}</h6>
                                    <span>{{ last_3_post.created_at }}</span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="blog__sidebar__item">
                        <h4>Search By</h4>
                        <div class="blog__sidebar__item__tags">
                            {% for tag in tags %}
                                <a href="/blog/?tag={{ tag }}">{{ tag }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-7 order-md-1 order-1">
                <div class="blog__details__text">
                    <h3>{{ post.title }}</h3>
                    <p>{{ post.content }}</p>
                    <img width="1000px" height="450px" src="{{ post.image.url }}" alt="">
                </div>
                <div class="blog__details__content">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="blog__details__author">
                                <div class="blog__details__author__pic">
                                    <img src="{{ post.author_image.url }}" alt="">
                                </div>
                                <div class="blog__details__author__text">
                                    <h6>{{ post.author_name }}</h6>
                                    <span>{{ post.author }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="blog__details__widget">
                                <ul>
                                    <li><span>Categories:</span> {{ post.category }}</li>
                                    <li><span>Tags:</span> {% for i in post.tags.all %}{{ i.tag }}, {% endfor %}</li>
                                </ul>
                                <div class="blog__details__social">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-google-plus"></i></a>
                                    <a href="#"><i class="fa fa-linkedin"></i></a>
                                    <a href="#"><i class="fa fa-envelope"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="related-blog spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title related-blog-title">
                    <h2>Post You May Like</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for last_3_post in last_3_posts %}
                <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="{{ last_3_post.image.url }}" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> {{ last_3_post.created_at }}</li>
                        </ul>
                        <h5><a href="/blog/blog-details/{{ last_3_post.id }}">{{ last_3_post.title|slice:100 }}</a></h5>
                        <p>{{ last_3_post.content|slice:255 }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="hero hero-normal">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All categories</span>
                    </div>
                    <ul>
                        {% for category in categories %}
                            <li><a href=".">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form method="get">
                            <input type="search" name="s" placeholder="What do you need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>+998 88 910 67 63</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="breadcrumb-section set-bg" data-setbg="{% static 'img/blog/details/details-hero.jpg.webp' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Blog</h2>
                    <div class="breadcrumb__option">
                        <a href="/">Home</a>
                        <span>Blog</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="blog spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-5">
                <div class="blog__sidebar">
                    <div class="blog__sidebar__search">
                        <form method="get">
                            <input type="search" name="s" placeholder="Search...">
                            <button type="submit"><span class="icon_search"></span></button>
                        </form>
                    </div>
                    <div class="blog__sidebar__item">
                        <h4>Categories</h4>
                        <ul>
                            {% for category in categories %}
                                <li><a href="?cat={{ category }}">{{ category }} ({{ category.post_set.count }})</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="blog__sidebar__item">
                        <h4>Recent News</h4>
                        <div class="blog__sidebar__recent">
                            {% for last_3_post in last_3_posts %}
                                <a href="{% url 'blog:blog-details' last_3_post.id %}" class="blog__sidebar__recent__item">
                                <div class="blog__sidebar__recent__item__pic">
                                    <img width="90px" height="80px" src="{{ last_3_post.image.url }}" alt="">
                                </div>
                                <div class="blog__sidebar__recent__item__text">
                                    <h6>{{ last_3_post.title|slice:75 }}</h6>
                                    <span>{{ last_3_post.created_at }}</span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="blog__sidebar__item">
                        <h4>Search By</h4>
                        <div class="blog__sidebar__item__tags">
                            {% for tag in tags %}
                                <a href="?tag={{ tag }}">{{ tag }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-7">
                <div class="row">
                    {% for post in posts %}
                        <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic">
                                <img src="{{ post.image.url }}" alt="">
                            </div>
                            <div class="blog__item__text">
                                <ul>
                                    <li><i class="fa fa-calendar-o"></i> {{ post.created_at }}</li>
                                </ul>
                                <h5><a href="/blog/blog-details/{{ post.id }}">{{ post.title }}</a></h5>
                                <p>{{ post.content|slice:250 }}</p>
                                <a href="/blog/blog-details/{{ post.id }}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col-lg-12">
                        <div class="product__pagination blog__pagination">
                            <a href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block scripts %}
<script>
$('.header__menu>ul>li').removeClass('active')
$('.blog_page').addClass('active')
</script>
{% endblock %}

templates/my-wishlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="hero hero-normal">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All categories</span>
                    </div>
                    <ul>
                        {% for category in categories %}
                            <li><a href="#">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form method="get">
                            <input type="search" name="s" placeholder="What do you need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>+998 90 810 67 63</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="breadcrumb-section set-bg" data-setbg="{% static 'img/blog/details/details-hero.jpg.webp' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Ogani Shop</h2>
                    <div class="breadcrumb__option">
                        <a href="/">Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-5">
                <div class="sidebar">
                    <div class="sidebar__item">
                        <h4>Categories</h4>
                        <ul>
                            {% for category in categories %}
                                <li><a href="#">{{ category }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar__item">
                        <div class="latest-product__text">
                            <h4>Latest Products</h4>
                            <div class="latest-product__slider owl-carousel">
                                <div class="latest-prdouct__slider__item">
                                    {% for latest_product in latest_products|slice:':3' %}
                                        <a href="#" class="latest-product__item">
                                            <div class="latest-product__item__pic">
                                                <img src="{{ latest_product.product_image.first.image.url }}" alt="">
                                            </div>
                                            <div class="latest-product__item__text">
                                                <h6>{{ latest_product.name }}</h6>
                                                <span>UZS {{ latest_product.price }}</span>
                                                <pre><code><i class="fa fa-eye"></i> : {{ latest_product.views }}</code></pre>
                                                <pre><code><i class="fa fa-star-half-o"></i> : {{ latest_product.get_mid_rate }}</code></pre>
                                            </div>
                                        </a>
                                    {% endfor %}
                                </div>
                                <div class="latest-prdouct__slider__item">
                                    {% for latest_product in latest_products|slice:'3:' %}
                                        <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ latest_product.product_image.first.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{ latest_product.name }}</h6>
                                    <span>UZS {{ latest_product.price }}</span>
                                    <pre><code><i class="fa fa-eye"></i> : {{ latest_product.views }}</code></pre>
                                    <pre><code><i class="fa fa-star-half-o"></i> : {{ latest_product.get_mid_rate }}</code></pre>
                                </div>
                            </a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-7">
                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-4">
                            <div class="filter__found">
                                <h6><span>{{ request.user.wishlist.count }}</span> Products found</h6>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="product__item">
                            <div class="product__item__pic set-bg" data-setbg="{{ product.product.product_image.first.image.url }}">
                                <ul class="product__item__pic__hover">
                                    <li><a class="add-wishlist" data-product="{{ product.product.id }}"><i class="fa fa-heart-circle-minus"></i></a></li>
                                    <li><a class="add-cart" data-product="{{ product.product.id }}"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                            </div>
                            <div class="product__item__text">
                                <h6><a href="{% url 'products:shop-details' product.id  %}">{{ product.product.name }}</a></h6>
                                <h5>UZS {{ product.product.price }}</h5>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="product__pagination">
                    <a href="#">1</a>
                    <a href="#">2</a>
                    <a href="#">3</a>
                    <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="first_name">First Name</label>
            <input name="first_name" class="form-control" id="first_name" type="text" placeholder="Enter your first name" value="{{ profile.user.first_name }}" required>
        </div>
        <div>
            <label for="last_name">Last Name</label>
            <input name="last_name" class="form-control" id="last_name" type="text" placeholder="Also your last name" value="{{ profile.user.last_name }}" required>
        </div>
        <label for="gender">Gender</label>
        <select name="gender" class="form-select mb-0" id="gender"
                aria-label="Gender select example">
            <option selected>Gender</option>
            {% for key, value in profile.GENDER_CHOICES %}
                <option value="{{ key }}"
                        {% if profile.gender == key %}selected{% endif %}>{{ value }}</option>
            {% endfor %}
        </select>
    </form>

{% endblock %}